services:
  nginx:
    restart: always
    depends_on:
      - docs
      - blog
      - app
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx/dev
    ports:
      - "4500:80"
  docs:
    build:
      dockerfile: ./apps/docs/Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - /app/apps/docs/node_modules
      - /app/apps/docs/.next
      - ./apps/docs:/app/apps/docs
  app:
    build:
      dockerfile: ./apps/app/Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - /app/apps/app/node_modules
      - /app/apps/app/.next
      - ./apps/app:/app/apps/app
  blog:
    build:
      dockerfile: ./apps/blog/Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - /app/node_modules
      - /app/apps/blog/.next
      - ./apps/blog:/app/apps/blog



