include:
  - ./apps/app/docker-compose-dev.yml
  - ./apps/blog/docker-compose-dev.yml
  - ./apps/docs/docker-compose-dev.yml
services:
  nginx:
    restart: always
    depends_on:
      - docs
      - blog
      - app
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx/dev
    ports:
      - "4500:80"



