name: Deploy mfes
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin

      - run: docker build -t sameroso/docs -f ./apps/docs/Dockerfile .
      - run: docker build -t sameroso/blog -f ./apps/blog/Dockerfile .
      - run: docker build -t sameroso/listingproducts -f ./apps/listingProducts/Dockerfile .
      - run: docker build -t sameroso/app -f ./apps/app/Dockerfile .

      - run: docker push sameroso/docs
      - run: docker push sameroso/blog
      - run: docker push sameroso/listingproducts
      - run: docker push sameroso/app
