name: Deploy mfes
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - run: docker build -t sameroso/docs -f ./apps/docs/Dockerfile .
      - run: docker build -t sameroso/blog -f ./apps/blog/Dockerfile .
      - run: docker build -t sameroso/listingproducts -f ./apps/listingProducts/Dockerfile .
      - run: docker build -t sameroso/app -f ./apps/app/Dockerfile .
      - run: docker build -t sameroso/nginx ./nginx/prod

      - run: docker push sameroso/docs
      - run: docker push sameroso/blog
      - run: docker push sameroso/listingproducts
      - run: docker push sameroso/app
      
      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: mfe-docker
          environment_name: Mfe-docker-env-1
          version_label: "mfe-docker: ${{ github.sha }}"
          region: us-east-1
          deployment_package: deploy.zip
